# Configuração do Server
#server.port=8080

# Configuração do Banco de Dados
#spring.datasource.url=jdbc:postgresql://localhost:5432/futeboldb
#spring.datasource.username=postgres
#spring.datasource.password=elaia
#spring.jpa.hibernate.ddl-auto=update

# Configuração do Banco de Dados (H2)
#spring.datasource.url=jdbc:h2:mem:futebol_db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#pring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite que o Spring crie as tabelas automaticamente baseado no seu código
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring está executando (bom para testar)
#spring.jpa.show-sql=true

# Ativa o console do H2 para você ver o banco no navegador
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Ativa o console do H2
spring.h2.console.enabled=true

# Define o caminho para acessar (será http://localhost:8080/h2-console)
spring.h2.console.path=/h2-console

# Configurações do banco (Garanta que são as mesmas que você usa no código)
spring.datasource.url=jdbc:h2:mem:futebol_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Para evitar erros de frames no console do H2
spring.h2.console.settings.web-allow-others=true